### ISSUE TITLE
Crash on world unload - only Fields of Gold enabled

### ISSUE THREAD

**Issue by ana-luna-v** [VinterNacht/FieldsOfGold#2]
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.4-rc.2 (Unstable)
Loaded Mods: fieldsofgold@1.1.8, game@1.16.4-rc.2, creative@1.16.4-rc.2, survival@1.16.4-rc.2
3/1/2022 6:44:34 PM: Critical error occurred
System.MissingMethodException: Method not found: '!!0 Vintagestory.API.Common.IModLoader.GetModSystem()'.
   at FieldsOfGold.BlockEntities.FOGBerryBush.OnBlockUnloaded()
   at Vintagestory.Client.NoObf.SystemUnloadChunks.UnloadChunk(ClientChunk clientchunk)
   at Vintagestory.Client.NoObf.SystemUnloadChunks.Dispose(ClientMain game)
   at Vintagestory.Client.NoObf.ClientMain.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected)
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at _As7FGAmUC8gaKIkRNk2zuk1jlJ._zleiWFUbDyAE8J9zHf00bJUUlQr(_M5s9po0jOCy75F2Bz2DU6XdfcDb , String[] )
   at _f8y3Fmmhb3dxIjBj0LM71AeVhBG._zleiWFUbDyAE8J9zHf00bJUUlQr(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/1/2022 12:35:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1507433074442249010, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\thego\AppData\Local\Temp\RDR8257.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8268.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8278.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8296.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER82B6.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: da9d75da-e8d2-4eb7-844a-663877911d32
Report Status: 268435456
Hashed bucket: 51a26c0cf8d337ea14eb7a64fcce2332
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/16/2021 2:29:40 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1507433074442249010, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\thego\AppData\Local\Temp\RDR4601.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4621.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4641.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER466E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER468E.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: d2751171-6585-4c5d-a82e-f97b2f9e17cd
Report Status: 268435456
Hashed bucket: 51a26c0cf8d337ea14eb7a64fcce2332
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/5/2021 9:26:46 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1507433074442249010, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.1.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\thego\AppData\Local\Temp\RDR4B63.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B83.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B94.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4BC1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4BE1.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9cc33eaf-fffd-4c43-9f2d-f77a7307221c
Report Status: 268435456
Hashed bucket: 51a26c0cf8d337ea14eb7a64fcce2332
Cab Guid: 0 }

**Comment by VinterNacht** [comment]
Fixed in latest updates.
