### ISSUE TITLE
Crash when right-clicking haystack with a block of hay

### ISSUE THREAD

**Issue by XxNinMario64xX** [VinterNacht/FieldsOfGold#4]
As said in the title. Crash report below:

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: fieldsofgold@1.1.12, sticksfromfirewood@1.16.4, game@1.16.4, creative@1.16.4, survival@1.16.4
3/30/2022 10:31:33 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at FieldsOfGold.BlockEntities.FOGBEHaystack.OnPlayerInteract(IPlayer byPlayer)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/24/2022 12:59:48 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ModCompilationContext..ctor()
   at Vintagestory.Common.ModLoader..ctor(Vintagestory.API.Common.ICoreAPI, Vintagestory.API.Common.EnumAppSide, Vintagestory.API.Common.ILogger, System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._ioMsa8O6C7r1QoM0T5O8oXq26g()
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._T3zQdFrI3HuT2KPhy3PcGxz9N4G()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 3/19/2022 10:30:38 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1715359538913174117, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\dkfpi\AppData\Local\Temp\RDRFDA.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFEA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFFB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1018.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1039.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: f39a03ba-7749-477d-9b12-a08f904d8969
Report Status: 268435456
Hashed bucket: 2de2e32f95852db547ce2e698aff6265
Cab Guid: 0 }

**Comment by VinterNacht** [comment]
Issue resolved in latest release.
