### ISSUE TITLE
Compatability issue

### ISSUE THREAD

**Issue by ObsidianDust** [VinterNacht/FieldsOfGold#6]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: advancedsmithing@1.2.0, chiseltools@1.3.1, collabclasses@3.0.3, dragonflies@1.2.0, expandedfoods@1.5.3-pre.4, fieldsofgold@1.1.12, foundrymod@1.0.0, glassmaking@1.2.0, hammersringingfall@1.1.1-rc.1, knappingmastery@1.0.1, potatoes@1.0.8, moredrygrass@0.2.0, moreminerals@1.0.2, leadroof@1.1.1, preservationmod@1.0.0, primitivesurvival@2.8.0, qptech@1.7.6, viescraftmachines@1.17.0, game@1.16.4, carrycapacity@0.6.5, farmlife@1.2.3, fromgoldencombs@1.3.11, lichen@1.6.1, medievalexpansion@3.7.1, moreanimals@1.2.2, morepiles@1.2.0, petai@1.3.7, prospectorinfo@3.1.2, stonequarry@1.6.5, usefulstuff@2.3.2, creative@1.16.4, survival@1.16.4, wildfarming@1.2.8, xrowboat@0.0.3, campaigncartographer@2.1.3, bricklayers@0.9.0, feverstonehorses@1.2.6, packanimals@1.0.1, wildcraft@1.2.1
2022-03-30 1:16:28 PM: Critical error occurred
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Single' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'inGameHours.*-liquorice-harvested', line 5, position 28.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Vintagestory.GameContent.BlockEntityTransient.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at wildcraft.LeafyGroundVegetable.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2022-03-30 1:13:21 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDR4936.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4947.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4948.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4965.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4985.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2814f749-30a3-47a9-8bc8-43a775027bd8
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-02-28 8:44:04 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDR82FA.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER830A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER830B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8329.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8349.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2fd97e91-f5f1-4fc8-8189-481b644b9249
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-01-29 8:42:44 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1302431364789752868, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.1.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDRB13A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB14A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB15B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB169.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB199.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: a1f29192-3550-42d6-9ba6-bfdeac93fd38
Report Status: 268435456
Hashed bucket: 63f31e0847fe955382132a6cfa9ed424
Cab Guid: 0 }

**Comment by VinterNacht** [comment]
ObsidianDust, what platform are you running this on? I've only seen this occur with Linux users.

**Comment by ObsidianDust** [comment]
Windows 10 never ran a linux system



Sent from my Galaxy



-------- Original message --------
From: Vinter_Nacht ***@***.***>
Date: 2022-03-30 2:36 PM (GMT-08:00)
To: VinterNacht/FieldsOfGold ***@***.***>
Cc: ObsidianDust ***@***.***>, Author ***@***.***>
Subject: Re: [VinterNacht/FieldsOfGold] Compatability issue (Issue #6)


ObsidianDust, what platform are you running this on? I've only seen this occur with Linux users.

**Comment by VinterNacht** [comment]
How bizarre.  You're one of two people who have reported this. I'll look deeper and see if I can suss out the issue.

**Comment by ObsidianDust** [comment]
I know I have quite a few mods so I'm not surprised there has been an issue



Sent from my Galaxy



-------- Original message --------
From: Vinter_Nacht ***@***.***>
Date: 2022-03-30 2:38 PM (GMT-08:00)
To: VinterNacht/FieldsOfGold ***@***.***>
Cc: ObsidianDust ***@***.***>, Author ***@***.***>
Subject: Re: [VinterNacht/FieldsOfGold] Compatability issue (Issue #6)


How bizarre. You're one of two people who have reported this. I'll look deeper and see if I can suss out the issue.

**Comment by Alice196498** [comment]
I get the ſame error :—
Loaded mods :
modorigin@/home/alice/ApplicationData/Vintage Story/assets/creative/, modorigin@/home/alice/ApplicationData/Vintage Story/assets/survival/, mod@BackpackPackStandard_v1.0.3.zip, mod@CreaturesandCritters1.2.0.zip, mod@ExpandedFoods 1.5.3-pre.4.zip, mod@FieldsOfGold-1.16_v1.1.12.zip, mod@HideAndFabric-1.1.0.zip, mod@humanlikeskintones_v0.0.1.zip, mod@MeteoricExpansion_V1.1.1.zip, mod@MoreCrops1.0.8.zip, mod@PrimitiveSurvival2.8.0.zip, mod@Stackables2.0.4.zip, mod@FromGoldenCombs-1.16_v1.3.11.zip, mod@gasapi_v1.0.2.zip, mod@MoreAnimals-1.2.2.zip, mod@petai_v1.3.7.zip, mod@PlayerCorpse_v1.16.3_v1.3.1.zip, mod@sandsoftime-1.0.1.zip, mod@StoneQuarry_v1.16.4_v1.6.5.zip, mod@vsvillage_v0.0.3.zip, mod@AnvilMetalRecovery_V0.1.17_Release.zip, mod@Bullseye 2.2.4.zip, mod@FeverstoneHorses-v1.2.6-1.16.x.zip, mod@PackAnimals1.0.1.zip, mod@wildcraft-v1.2.1.zip

Error :
Exception thrown when trying to initialize a block entity @511879, 113, 532531: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Single' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'inGameHours.*-liquorice-harvested', line 5, position 28.
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0038e] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) [0x00061] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x00267] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00161] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <5753133c467642479854e5d6c1dc2798>:0 
  at Vintagestory.API.Datastructures.JsonObject.AsObject[T] (T defaultValue) [0x00015] in <c35009a825774beb829bbd8af877cce6>:0 
  at Vintagestory.GameContent.BlockEntityTransient.Initialize (Vintagestory.API.Common.ICoreAPI api) [0x00044] in <ad1e4c9c94964f80bb4961e988726d22>:0 
  at Vintagestory.Server.ServerSystemSupplyChunks+<>c__DisplayClass15_0.<loadOrGenerateChunkColumn>b__0 () [0x0019f] in <6b6988c5e6264e7e8b7a32e875df9528>:0

Further notes :
It appears to throw the error more in my world when I ſet the view diſtance higher.

**Comment by ObsidianDust** [comment]
Weird iv gotten it every time I harvested any herb even from a fresh reload.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by VinterNacht** [comment]
Alright folks, I've reached the end of my ability here.  I took all the mods you have in common and tested it on my machine. There's no crash. Whatever this is is somehow related to something your two setups have in common.. God only knows what that may be.

I tried harvesting every herb, and got no crash.  Unsure where to go from here.

**Comment by VinterNacht** [comment]
It appears to be fixed in the latest release. However, I have no idea what was causing it, or rather, why it was *only* in effect for two people.

**Comment by ObsidianDust** [comment]
Are you sure about that cause it's still doing it for me spawned in moved to plant harvested and crashed



Sent from my Galaxy



-------- Original message --------
From: Vinter_Nacht ***@***.***>
Date: 2022-03-30 8:08 PM (GMT-08:00)
To: VinterNacht/FieldsOfGold ***@***.***>
Cc: ObsidianDust ***@***.***>, Author ***@***.***>
Subject: Re: [VinterNacht/FieldsOfGold] Compatability issue (Issue #6)


It appears to be fixed in the latest release. However, I have no idea what was causing it, or rather, why it was only in effect for two people.

**Comment by ObsidianDust** [comment]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: advancedsmithing@1.2.0, chiseltools@1.3.1, collabclasses@3.0.3, dragonflies@1.2.0, expandedfoods@1.5.3-pre.4, fieldsofgold@1.1.13, foundrymod@1.0.0, glassmaking@1.2.0, hammersringingfall@1.1.2-rc.1, knappingmastery@1.0.1, potatoes@1.0.8, moredrygrass@0.2.0, moreminerals@1.0.2, leadroof@1.1.1, preservationmod@1.0.0, primitivesurvival@2.8.0, qptech@1.7.6, viescraftmachines@1.17.0, game@1.16.4, carrycapacity@0.6.5, farmlife@1.2.3, fromgoldencombs@1.3.11, lichen@1.6.1, medievalexpansion@3.7.1, moreanimals@1.2.2, morepiles@1.2.0, petai@1.3.7, prospectorinfo@3.1.2, stonequarry@1.6.5, usefulstuff@2.3.2, creative@1.16.4, survival@1.16.4, wildfarming@1.2.8, xrowboat@0.0.3, campaigncartographer@2.1.3, bricklayers@0.9.0, feverstonehorses@1.2.6, packanimals@1.0.1, wildcraft@1.2.1
2022-03-30 8:15:25 PM: Critical error occurred
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Single' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'inGameHours.*-yarrow-harvested', line 5, position 25.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Vintagestory.GameContent.BlockEntityTransient.Initialize(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at wildcraft.LeafyGroundVegetable.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2022-03-30 1:13:21 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDR4936.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4947.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4948.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4965.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4985.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2814f749-30a3-47a9-8bc8-43a775027bd8
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-02-28 8:44:04 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDR82FA.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER830A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER830B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8329.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8349.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2fd97e91-f5f1-4fc8-8189-481b644b9249
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-01-29 8:42:44 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1302431364789752868, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.1.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDRB13A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB14A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB15B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB169.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB199.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a1f29192-3550-42d6-9ba6-bfdeac93fd38
Report Status: 268435456
Hashed bucket: 63f31e0847fe955382132a6cfa9ed424
Cab Guid: 0 }
